### ISSUE TITLE
Needs to be updated - v1.79 of HIBP Offline Check available

### ISSUE THREAD

**Issue by AIVAS001** [koitsu/chocolatey-packages#1]
Chocolatey package, keepass-plugin-hibpofflinecheck, needs to be updated - v1.79 of HIBP Offline Check available

https://github.com/mihaifm/HIBPOfflineCheck/releases/tag/1.7.9

Thanks

**Comment by koitsu** [comment]
Thanks!  Chocolatey package for 1.7.9 has been pushed to the Community Repository.  Should be available in a few days or weeks, depending on moderator response time.  Refer to https://community.chocolatey.org/packages/keepass-plugin-hibpofflinecheck/1.7.9 or https://ch0.co/moderation for progress.
